/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'contact-reasons': ContactReason;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-reasons': ContactReasonsSelect<false> | ContactReasonsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-reasons".
 */
export interface ContactReason {
  id: number;
  /**
   * Texto visible en el dropdown del formulario de contacto y en el asunto del correo.
   */
  label: string;
  /**
   * Identificador estable (no traducido), ej. product-quote. Usado internamente para enlazar CTAs.
   */
  key: string;
  /**
   * Controla el orden en el dropdown (menor primero).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Identificador estable, ej. naranjilla. No se traduce.
   */
  slug: string;
  name: string;
  /**
   * Nombre científico (binomio latino). No se traduce.
   */
  scientificName?: string | null;
  description?: string | null;
  /**
   * Color de acento libre (hex), ej. #7B3F99.
   */
  accentColor?: string | null;
  mainImage: number | Media;
  topImage: number | Media;
  bottomImage: number | Media;
  /**
   * Flor decorativa en la esquina de la tarjeta (opcional).
   */
  bloomImage?: (number | null) | Media;
  /**
   * Ícono neutro (se recolorea con el color de acento). Opcional.
   */
  arrowIcon?: (number | null) | Media;
  /**
   * Los 4 datos del grid (origen, sabor, temporada, transporte).
   */
  stats?:
    | {
        icon?: (number | null) | Media;
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ficha técnica en PDF.
   */
  technicalSheet?: (number | null) | Media;
  /**
   * Orden de aparición (menor primero).
   */
  displayOrder?: number | null;
  featuredOnHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-reasons';
        value: number | ContactReason;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-reasons_select".
 */
export interface ContactReasonsSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  scientificName?: T;
  description?: T;
  accentColor?: T;
  mainImage?: T;
  topImage?: T;
  bottomImage?: T;
  bloomImage?: T;
  arrowIcon?: T;
  stats?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  technicalSheet?: T;
  displayOrder?: T;
  featuredOnHomepage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand?: {
    /**
     * Usado en Header (hero) y Footer, sobre fondos oscuros.
     */
    logoOnDark?: (number | null) | Media;
    /**
     * Usado en Header sobre fondos claros (ej. página de Contacto).
     */
    logoOnLight?: (number | null) | Media;
  };
  header: {
    navNosotros: string;
    navPorQueElegirnos: string;
    navProductos: string;
    navContacto: string;
    logoAlt?: string | null;
    ariaOpenMenu?: string | null;
    ariaCloseMenu?: string | null;
    ariaMainNav?: string | null;
  };
  footer?: {
    description?: string | null;
    followUsLabel?: string | null;
    /**
     * Redes sociales (Instagram, LinkedIn, etc). WhatsApp y email tienen sus propios campos abajo.
     */
    socialLinks?:
      | {
          platform: 'instagram' | 'linkedin' | 'facebook' | 'email' | 'other';
          url: string;
          /**
           * Texto accesible (aria-label) del ícono.
           */
          label?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Razón social, ej. QuintanaGlobalHarvest S.A.S. No se traduce.
     */
    copyrightLegalName?: string | null;
    devCredit?: string | null;
  };
  contact?: {
    contactHeading?: string | null;
    locationLine?: string | null;
    email?: string | null;
    website?: string | null;
    /**
     * Formato E.164, ej. +593939664770.
     */
    whatsappNumber?: string | null;
    /**
     * Mensaje precargado al abrir WhatsApp. Ahora sí varía por idioma.
     */
    whatsappMessageTemplate?: string | null;
  };
  seoDefaults?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    ogImage?: (number | null) | Media;
    orgName?: string | null;
    orgLegalName?: string | null;
    orgAddressLocality?: string | null;
    orgAddressCountry?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    titleLine1: string;
    titleLine2Prefix?: string | null;
    titleAccent?: string | null;
    subtitleLine1?: string | null;
    subtitleLine2?: string | null;
    ctaLabel?: string | null;
    /**
     * Motivo precargado en el formulario de contacto al hacer clic en el CTA.
     */
    ctaReason?: (number | null) | ContactReason;
    /**
     * Las 3 fotos de fondo del Hero (escritorio: columnas; móvil: slideshow).
     */
    backgroundImages?:
      | {
          image: number | Media;
          /**
           * Identifica la posición/columna, no depende del orden del array. 'Granadilla' tiene un encuadre especial (foto emparejada) en el CSS.
           */
          columnKey: 'purple' | 'tamarillo' | 'granadilla';
          zoom?: number | null;
          panY?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  nosotros?: {
    /**
     * Las 3 imágenes decorativas con efecto parallax.
     */
    floatingImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    bloque1?: {
      headingLine1?: string | null;
      headingLine2?: string | null;
      headingAccent?: string | null;
      /**
       * El párrafo principal, dividido en fragmentos. Marca 'highlight' para resaltar en naranja.
       */
      bodyFragments?:
        | {
            text: string;
            highlight?: boolean | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Los íconos con texto debajo del párrafo (ej. Cultivo responsable, Trazabilidad...).
       */
      features?:
        | {
            icon: number | Media;
            /**
             * Usa saltos de línea para controlar el corte de línea.
             */
            label: string;
            id?: string | null;
          }[]
        | null;
      /**
       * La foto grande (huerto).
       */
      featuredImage?: (number | null) | Media;
      featuredImageAlt?: string | null;
    };
    bloque2?: {
      compromisoPrefix?: string | null;
      compromisoAccent?: string | null;
      compromisoBody?: string | null;
      /**
       * Las 2 fotos de galería.
       */
      featuredImages?:
        | {
            image: number | Media;
            alt?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  porQueElegirnos?: {
    headingPrefix?: string | null;
    headingAccent?: string | null;
    body?: string | null;
    captionText?: string | null;
    /**
     * Tarjetas de la sección — crear, editar, eliminar y reordenar libremente.
     */
    cards?:
      | {
          image: number | Media;
          imageAlt?: string | null;
          icon: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Solo el copy de la sección — los productos en sí se administran en la colección Products.
   */
  productos?: {
    heading?: string | null;
    subheading?: string | null;
    ctaFichaLabel?: string | null;
    ctaCotizarLabel?: string | null;
    ctaCotizarReason?: (number | null) | ContactReason;
  };
  /**
   * Franja de confianza al final de Productos.
   */
  beneficios?: {
    heading?: string | null;
    /**
     * Crear, editar, eliminar y reordenar libremente.
     */
    items?:
      | {
          icon: number | Media;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seo?: {
    pageTitle?: string | null;
    pageDescription?: string | null;
  };
  headingPrefix?: string | null;
  headingAccent?: string | null;
  headingSuffix?: string | null;
  /**
   * El texto antes del enlace mailto (el email en sí viene de Ajustes del sitio).
   */
  subtextPrefix?: string | null;
  cardHeading?: string | null;
  form?: {
    empresaLabel?: string | null;
    nombreLabel?: string | null;
    apellidosLabel?: string | null;
    emailLabel?: string | null;
    asuntoLabel?: string | null;
    comentarioLabel?: string | null;
    privacyPrefix?: string | null;
    privacyLinkLabel?: string | null;
    /**
     * Aún no existe una página de política de privacidad real — placeholder hasta que se publique.
     */
    privacyPolicyUrl?: string | null;
    submitLabel?: string | null;
    sendingLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        logoOnDark?: T;
        logoOnLight?: T;
      };
  header?:
    | T
    | {
        navNosotros?: T;
        navPorQueElegirnos?: T;
        navProductos?: T;
        navContacto?: T;
        logoAlt?: T;
        ariaOpenMenu?: T;
        ariaCloseMenu?: T;
        ariaMainNav?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        followUsLabel?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
        copyrightLegalName?: T;
        devCredit?: T;
      };
  contact?:
    | T
    | {
        contactHeading?: T;
        locationLine?: T;
        email?: T;
        website?: T;
        whatsappNumber?: T;
        whatsappMessageTemplate?: T;
      };
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
        orgName?: T;
        orgLegalName?: T;
        orgAddressLocality?: T;
        orgAddressCountry?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titleLine1?: T;
        titleLine2Prefix?: T;
        titleAccent?: T;
        subtitleLine1?: T;
        subtitleLine2?: T;
        ctaLabel?: T;
        ctaReason?: T;
        backgroundImages?:
          | T
          | {
              image?: T;
              columnKey?: T;
              zoom?: T;
              panY?: T;
              id?: T;
            };
      };
  nosotros?:
    | T
    | {
        floatingImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        bloque1?:
          | T
          | {
              headingLine1?: T;
              headingLine2?: T;
              headingAccent?: T;
              bodyFragments?:
                | T
                | {
                    text?: T;
                    highlight?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              featuredImage?: T;
              featuredImageAlt?: T;
            };
        bloque2?:
          | T
          | {
              compromisoPrefix?: T;
              compromisoAccent?: T;
              compromisoBody?: T;
              featuredImages?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
            };
      };
  porQueElegirnos?:
    | T
    | {
        headingPrefix?: T;
        headingAccent?: T;
        body?: T;
        captionText?: T;
        cards?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  productos?:
    | T
    | {
        heading?: T;
        subheading?: T;
        ctaFichaLabel?: T;
        ctaCotizarLabel?: T;
        ctaCotizarReason?: T;
      };
  beneficios?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
      };
  headingPrefix?: T;
  headingAccent?: T;
  headingSuffix?: T;
  subtextPrefix?: T;
  cardHeading?: T;
  form?:
    | T
    | {
        empresaLabel?: T;
        nombreLabel?: T;
        apellidosLabel?: T;
        emailLabel?: T;
        asuntoLabel?: T;
        comentarioLabel?: T;
        privacyPrefix?: T;
        privacyLinkLabel?: T;
        privacyPolicyUrl?: T;
        submitLabel?: T;
        sendingLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}